local InventoryPrefabsList = {  --每个元素的下标值为每种物品栏图片的名字
	rosorns = { build = "images_minisign1" },
    lileaves =  { build = "images_minisign1" },
    orchitwigs = { build = "images_minisign1" },
    neverfade = { build = "images_minisign1" },
    neverfade_broken = { build = "images_minisign1" },
    sachet = { build = "images_minisign1" },
    petals_rose = { build = "images_minisign1" },
    petals_lily = { build = "images_minisign1" },
    petals_orchid = { build = "images_minisign1" },
    dug_rosebush = { build = "images_minisign1" },
    --10

    dug_lilybush = { build = "images_minisign1" },
    dug_orchidbush = { build = "images_minisign1" },
    cutted_rosebush = { build = "images_minisign1" },
    cutted_orchidbush = { build = "images_minisign1" },
    cutted_lilybush = { build = "images_minisign1" },
    -- portablecookpot_item = { build = "images_minisign1" },
    hat_cowboy = { build = "images_minisign1" },
    desertdefense = { build = "images_minisign1" },
    hat_lichen = { build = "images_minisign1" },
    agronssword = { build = "images_minisign1" },
    agronssword2 = { build = "images_minisign1" },
    --20

    dish_chilledrosejuice = { build = "images_minisign2" },
    dish_twistedrolllily = { build = "images_minisign2" },
    dish_orchidcake = { build = "images_minisign2" },
    dish_ricedumpling = { build = "images_minisign2" },
    dish_duriantartare = { build = "images_minisign2" },
    dish_fleshnapoleon = { build = "images_minisign2" },
    dish_beggingmeat = { build = "images_minisign2" },
    dish_frenchsnailsbaked = { build = "images_minisign2" },
    dish_neworleanswings = { build = "images_minisign2" },
    dish_fishjoyramen = { build = "images_minisign2" },
    --30

    dish_roastedmarshmallows = { build = "images_minisign2" },
    dish_pomegranatejelly = { build = "images_minisign2" },
    dish_medicinalliquor = { build = "images_minisign2" },
    dish_bananamousse = { build = "images_minisign2" },
    book_weather = { build = "images_minisign2" },
    giantsfoot = { build = "images_minisign2" },
    hat_mermbreathing = { build = "images_minisign2" },
    merm_scales = { build = "images_minisign2" },
    monstrain_leaf = { build = "images_minisign2" },
    raindonate = { build = "images_minisign2" },
    --40

    squamousfruit = { build = "images_minisign3" },
    refractedmoonlight = { build = "images_minisign3" },
    fimbul_axe = { build = "images_minisign3" },
    backcub = { build = "images_minisign3" },
    dish_merrychristmassalad = { build = "images_minisign3" },
    dualwrench = { build = "images_minisign3" },
    tourmalinecore = { build = "images_minisign3" },
    icire_rock1 = { build = "images_minisign3" },
    icire_rock2 = { build = "images_minisign3" },
    icire_rock3 = { build = "images_minisign3" },
    --50

    icire_rock4 = { build = "images_minisign3" },
    icire_rock5 = { build = "images_minisign3" },
    guitar_miguel = { build = "images_minisign3" },
    web_hump_item = { build = "images_minisign3" },
    saddle_baggage = { build = "images_minisign3" },
    shyerry = { build = "images_minisign3" },
    shyerry_cooked = { build = "images_minisign3" },
    shyerrylog = { build = "images_minisign3" },
    farmingdungball_item = { build = "images_minisign3" },
    pineananas = { build = "images_minisign3" },
    --60

    pineananas_cooked = { build = "images_minisign4" },
    pineananas_seeds = { build = "images_minisign4" },
    fence_shyerry_item = { build = "images_minisign4" },
    dish_murmurananas = { build = "images_minisign4" },
    dish_shyerryjam = { build = "images_minisign4" },
    ahandfulofwings = { build = "images_minisign4" },
    insectshell_l = { build = "images_minisign4" },
    boltwingout = { build = "images_minisign4" },
    tripleshovelaxe = { build = "images_minisign4" },
    catmint = { build = "images_minisign4" },
    cattenball = { build = "images_minisign4" },
    --71

    dish_sugarlesstrickmakercupcakes = { build = "images_minisign4" },
    hat_albicans_mushroom = { build = "images_minisign4" },
    soul_contracts = { build = "images_minisign4" },
    dish_flowermooncake = { build = "images_minisign4" },
    guitar_whitewood = { build = "images_minisign4" },
    toy_spongebob = { build = "images_minisign4" },
    toy_patrickstar = { build = "images_minisign4" },
    pinkstaff = { build = "images_minisign4" },
    theemperorscrown = { build = "images_minisign4" },
    theemperorsmantle = { build = "images_minisign4" },
    theemperorsscepter = { build = "images_minisign4" },
    --81

    foliageath = { build = "images_minisign5" },
    foliageath_rosorns = { build = "images_minisign5" },
    foliageath_lileaves = { build = "images_minisign5" },
    foliageath_orchitwigs = { build = "images_minisign5" },
    foliageath_neverfade = { build = "images_minisign5" },
    foliageath_hambat = { build = "images_minisign5" },
    foliageath_bullkelp_root = { build = "images_minisign5" },
    foliageath_foliageath = { build = "images_minisign5" },
    hiddenmoonlight_item = { build = "images_minisign5" },
    dish_farewellcupcake = { build = "images_minisign5" },
    --91

    dish_braisedmeatwithfoliages = { build = "images_minisign5" },
    dish_wrappedshrimppaste = { build = "images_minisign5" },
    albicans_cap = { build = "images_minisign5" },
    theemperorspendant = { build = "images_minisign5" },
    pineananas_oversized = { build = "images_minisign5" },
    pineananas_oversized_waxed = { build = "images_minisign5" },
    dish_sosweetjarkfruit = { build = "images_minisign5" },
    dish_friedfishwithpuree = { build = "images_minisign5" },
    siving_derivant_item = { build = "images_minisign5" },
    siving_soil_item = { build = "images_minisign5" },
    --101

    siving_rocks = { build = "images_minisign6" },
    siving_ctlwater_item = { build = "images_minisign6" },
    siving_ctldirt_item = { build = "images_minisign6" },
    pineananas_oversized_rotten = { build = "images_minisign6" },
    explodingfruitcake = { build = "images_minisign6" },
    mat_whitewood_item = { build = "images_minisign6" },
    fishhomingtool_normal = { build = "images_minisign6" },
    fishhomingtool_awesome = { build = "images_minisign6" },
    fishhomingbait1 = { build = "images_minisign6" },
    fishhomingbait2 = { build = "images_minisign6" },
    fishhomingbait3 = { build = "images_minisign6" },
    triplegoldenshovelaxe = { build = "images_minisign6" },
    shield_l_sand = { build = "images_minisign6" },
    shield_l_log = { build = "images_minisign6" },
    mint_l = { build = "images_minisign6" },
    seeds_crop_l = { build = "images_minisign6" },
    seeds_crop_l2 = { build = "images_minisign6" },
    siving_feather_fake = { build = "images_minisign6" },
    siving_feather_real = { build = "images_minisign6" },
    dish_tomahawksteak = { build = "images_minisign6" },
    foliageath_dish_tomahawksteak = { build = "images_minisign6" },
    siving_mask = { build = "images_minisign6" },
    siving_mask_gold = { build = "images_minisign6" },
    siving_ctlall_item = { build = "images_minisign6" },
    dug_monstrain = { build = "images_minisign6" },
    revolvedmoonlight_item = { build = "images_minisign6" },
    revolvedmoonlight = { build = "images_minisign6" },
    revolvedmoonlight_pro = { build = "images_minisign6" },
    dish_lovingrosecake = { build = "images_minisign6" },
    hat_elepheetle = { build = "images_minisign6" },
    armor_elepheetle = { build = "images_minisign6" },
    lance_carrot_l = { build = "images_minisign6" },
    tissue_l_cactus = { build = "images_minisign6" },
    tissue_l_lureplant = { build = "images_minisign6" },

    --skins1
    hat_lichen_emo_que = { build = "images_minisign_skins1" },
    neverfade_thanks = { build = "images_minisign_skins1" },
    neverfade_thanks_broken = { build = "images_minisign_skins1" },
    foliageath_neverfade_thanks = { build = "images_minisign_skins1" },
    hat_cowboy_tvplay = { build = "images_minisign_skins1" },
    boltwingout_disguiser = { build = "images_minisign_skins1" },
    hat_lichen_disguiser = { build = "images_minisign_skins1" },
    orchitwigs_disguiser = { build = "images_minisign_skins1" },
    foliageath_orchitwigs_disguiser = { build = "images_minisign_skins1" },
    fishhomingtool_normal_thanks = { build = "images_minisign_skins1" },
    fishhomingtool_awesome_thanks = { build = "images_minisign_skins1" },
    fishhomingbait1_thanks = { build = "images_minisign_skins1" },
    fishhomingbait2_thanks = { build = "images_minisign_skins1" },
    fishhomingbait3_thanks = { build = "images_minisign_skins1" },
    icire_rock1_era = { build = "images_minisign_skins1" },
    icire_rock2_era = { build = "images_minisign_skins1" },
    icire_rock3_era = { build = "images_minisign_skins1" },
    icire_rock4_era = { build = "images_minisign_skins1" },
    icire_rock5_era = { build = "images_minisign_skins1" },
    shield_l_sand_era = { build = "images_minisign_skins1" },
    shield_l_sand_op = { build = "images_minisign_skins1" },
    shield_l_log_emo_pride = { build = "images_minisign_skins1" },
    shield_l_log_emo_fist = { build = "images_minisign_skins1" },
    shield_l_log_era = { build = "images_minisign_skins1" },
    lileaves_era = { build = "images_minisign_skins1" },
    foliageath_lileaves_era = { build = "images_minisign_skins1" },
    tripleshovelaxe_era = { build = "images_minisign_skins1" },
    triplegoldenshovelaxe_era = { build = "images_minisign_skins1" },
    icire_rock1_collector = { build = "images_minisign_skins1" },
    icire_rock2_collector = { build = "images_minisign_skins1" },
    icire_rock3_collector = { build = "images_minisign_skins1" },
    icire_rock4_collector = { build = "images_minisign_skins1" },
    icire_rock5_collector = { build = "images_minisign_skins1" },
    rosorns_collector = { build = "images_minisign_skins1" },
    foliageath_rosorns_collector = { build = "images_minisign_skins1" },
    lileaves_marble = { build = "images_minisign_skins1" },
    foliageath_lileaves_marble = { build = "images_minisign_skins1" },
    orchitwigs_marble = { build = "images_minisign_skins1" },
    foliageath_orchitwigs_marble = { build = "images_minisign_skins1" },
    rosorns_marble = { build = "images_minisign_skins1" },
    foliageath_rosorns_marble = { build = "images_minisign_skins1" },
    fimbul_axe_collector = { build = "images_minisign_skins1" },
    backcub_fans = { build = "images_minisign_skins1" },
    backcub_fans2 = { build = "images_minisign_skins1" },
    backcub_thanks = { build = "images_minisign_skins1" },
    icire_rock1_day = { build = "images_minisign_skins1" },
    icire_rock2_day = { build = "images_minisign_skins1" },
    icire_rock3_day = { build = "images_minisign_skins1" },
    icire_rock4_day = { build = "images_minisign_skins1" },
    icire_rock5_day = { build = "images_minisign_skins1" },
    neverfade_paper = { build = "images_minisign_skins1" },
    neverfade_paper_broken = { build = "images_minisign_skins1" },
    foliageath_neverfade_paper = { build = "images_minisign_skins1" },
    neverfade_paper2 = { build = "images_minisign_skins1" },
    neverfade_paper2_broken = { build = "images_minisign_skins1" },
    foliageath_neverfade_paper2 = { build = "images_minisign_skins1" },

    --skins2
    agronssword_taste = { build = "images_minisign_skins2" },
    agronssword_taste2 = { build = "images_minisign_skins2" },
    siving_feather_real_paper = { build = "images_minisign_skins2" },
    siving_feather_fake_paper = { build = "images_minisign_skins2" },
    soul_contracts_taste = { build = "images_minisign_skins2" },
    revolvedmoonlight_item_taste = { build = "images_minisign_skins2" },
    revolvedmoonlight_taste = { build = "images_minisign_skins2" },
    revolvedmoonlight_pro_taste = { build = "images_minisign_skins2" },
    revolvedmoonlight_item_taste2 = { build = "images_minisign_skins2" },
    revolvedmoonlight_taste2 = { build = "images_minisign_skins2" },
    revolvedmoonlight_pro_taste2 = { build = "images_minisign_skins2" },
    revolvedmoonlight_item_taste3 = { build = "images_minisign_skins2" },
    revolvedmoonlight_taste3 = { build = "images_minisign_skins2" },
    revolvedmoonlight_pro_taste3 = { build = "images_minisign_skins2" },
    revolvedmoonlight_item_taste4 = { build = "images_minisign_skins2" },
    revolvedmoonlight_taste4 = { build = "images_minisign_skins2" },
    revolvedmoonlight_pro_taste4 = { build = "images_minisign_skins2" },
    pinkstaff_tvplay = { build = "images_minisign_skins2" },
    siving_feather_real_collector = { build = "images_minisign_skins2" },
    siving_feather_fake_collector = { build = "images_minisign_skins2" },
    siving_ctlwater_item_era = { build = "images_minisign_skins2" },
    siving_ctldirt_item_era = { build = "images_minisign_skins2" },
    siving_ctlall_item_era = { build = "images_minisign_skins2" },
    siving_mask_era = { build = "images_minisign_skins2" },
    siving_mask_era2 = { build = "images_minisign_skins2" },
    siving_mask_gold_era = { build = "images_minisign_skins2" },
    siving_mask_gold_era2 = { build = "images_minisign_skins2" }
}

return InventoryPrefabsList
