
STRINGS.UI.CRAFTING_FILTERS.LG_TEACH = "乘风破浪"

STRINGS.NAMES.ICE_LITCHI = "贵妃冰球"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ICE_LITCHI = "清凉一夏！"

STRINGS.NAMES.SASHIMI = "柠檬鲈鱼片"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SASHIMI = "我想…适合喜欢吃生食的人…"

STRINGS.NAMES.HOT_FISH = "辣炒桂鱼"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HOT_FISH = "吃了暖暖身子…"

STRINGS.NAMES.LG_RICE = "白饭"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_RICE = "白饭可不能酿酒！"

STRINGS.NAMES.HONEY_CAKE = "金丝榴莲酥"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HONEY_CAKE = "甜甜蜜蜜.."

STRINGS.NAMES.LG_FISHCAKE = "鱼仔大饼"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_FISHCAKE = "你听说过画饼专家鱼仔吗？"

STRINGS.NAMES.LG_BIGMILK = "手摇奶昔"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_BIGMILK = "摇啊摇？"

STRINGS.NAMES.LG_DOGCAKE = "狗粮堡"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_DOGCAKE = "这是我为七夕节单身狗制作的..."

STRINGS.NAMES.RAIN_FLOWER_STONE = "雨花石"
STRINGS.RECIPE_DESC.RAIN_FLOWER_STONE = "石玲珑,夺巧工,帷幔重重,觅个相思梦"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAIN_FLOWER_STONE = "渺渺斜风吹细雨"

STRINGS.NAMES.LG_SCULPTURE = "雨花台"
STRINGS.RECIPE_DESC.LG_SCULPTURE = "万物无非我造，异质殊形皆妙"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_SCULPTURE = "看月见天心！"

STRINGS.NAMES.LG_GRANARY = "仓囷"
STRINGS.RECIPE_DESC.LG_GRANARY = "晨兴理荒秽，带月荷锄归"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_GRANARY = "风行思数数，粮食厌频频"

STRINGS.NAMES.LG_LITICHI = "荔枝"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_LITICHI = "一骑红尘妃子笑"

STRINGS.NAMES.LG_LITICHI_COOKED = "烘焙荔枝"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_LITICHI_COOKED = "无人知是荔枝来"

STRINGS.NAMES.LG_LITICHI_TREE = "荔枝乔木"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_LITICHI_TREE = "迷损东家蝴蝶，殷勤踏取青阳"

STRINGS.NAMES.DUG_LG_LITICHI_TREE = "荔枝枝芽"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_LG_LITICHI_TREE = "桃柳旧根株，春到红蔫绿茁"

STRINGS.NAMES.LG_LEMON = "柠檬"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_LEMON = "千古一灵根，本妙元明静"

STRINGS.NAMES.LG_LEMON_COOKED = "烘培柠檬"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_LEMON_COOKED = "昼夜六时长在意"

STRINGS.NAMES.LG_LEMON_TREE = "柠檬枝"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_LEMON_TREE = "不随风雨轻舒卷,触石凝然正性根"

STRINGS.NAMES.DUG_LG_LEMON_TREE = "柠檬幼种"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_LG_LEMON_TREE = "王母柠檬种我家，三千阳春始一花"

STRINGS.NAMES.LG_KING_MACE = "小王子权杖"
STRINGS.RECIPE_DESC.LG_KING_MACE = "草木黄落兮雁南飞"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_KING_MACE = "往事只堪哀，对景难排"

STRINGS.NAMES.LG_BLADE = "雨花战刃"
STRINGS.RECIPE_DESC.LG_BLADE = "白马千群浪涌，银山万叠天高"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_BLADE = "百川有余水，大海无满波！"

STRINGS.REPAIR_LG = "修复"

STRINGS.NAMES.LG_ACTININE = "海葵"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_ACTININE = "更无柳絮因风起"

STRINGS.NAMES.LG_ACTININE_COOKED = "烤海葵"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_ACTININE_COOKED = "未有葵花向日倾"

STRINGS.NAMES.LG_ACTININE_PLANT = "海葵礁石"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_ACTININE_PLANT = "面朝大海，春暖花开"

STRINGS.NAMES.LG_LEMON_DRIED = "柠檬片"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_LEMON_DRIED = "一年好景君须记，最是橙黄橘绿时"

STRINGS.NAMES.LG_LITICHI_DRIED = "荔枝果脯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_LITICHI_DRIED = "颠坑仆谷相枕藉，知是荔枝龙眼来"

STRINGS.NAMES.LG_DRAGONFRUIT_DRIED = "火龙果干"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_DRAGONFRUIT_DRIED = "斜日庭前风袅袅，碧油千片漏红珠"


STRINGS.NAMES.LG_DURIAN_DRIED = "榴莲千层"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_DURIAN_DRIED = "玉刻冰壶含露湿，斒斑似带湘娥泣"

STRINGS.NAMES.LG_POMEGRANATE_DRIED = "石榴耔"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_POMEGRANATE_DRIED = "蝉啸秋云槐叶齐，石榴香老庭枝低"

STRINGS.NAMES.LG_WATERMELON_DRIED = "西瓜片"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_WATERMELON_DRIED = "沔怀青齐间，万树荫平陆"

STRINGS.NAMES.LG_CAVE_BANANA_DRIED = "香蕉果脯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_CAVE_BANANA_DRIED = "谁云食之昏，匿知乃成俗"

STRINGS.NAMES.LG_BERRIES_DRIED = "浆果果脯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_BERRIES_DRIED = "广庭觞圣寿，以此参肴蔌"

STRINGS.NAMES.LG_FRUIT_RACK = "果干晾晒架"
STRINGS.RECIPE_DESC.LG_FRUIT_RACK = "采菊东篱下，悠然见南山"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_FRUIT_RACK = "谁知盘中餐，粒粒皆辛苦"

STRINGS.NAMES.LG_JELLY = "心冻了莓"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_JELLY = "青箬笠，绿蓑衣，斜风细雨不须归"

STRINGS.NAMES.LG_LEMON_JELLY = "冻柠蜜"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_LEMON_JELLY = "莫笑农家腊酒浑，丰年留客足鸡豚"

STRINGS.NAMES.LG_SOUP = "海葵浓汤"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_SOUP = "桂花香馅裹胡桃，江米如珠井水淘"

STRINGS.NAMES.LG_FISHGIRL = "人鱼公主"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LG_FISHGIRL = "云想衣裳花想容，春风拂槛露华浓"
