require "prefabutil"

--MakePlacer("_placer", "inst.AnimState:SetBank", "inst.AnimState:SetBuild", "inst.AnimState:PlayAnimation")

return 
MakePlacer("mandrake_planted_placer", "mandrake", "mandrake", "ground"),
MakePlacer("catcoonden_placer", "catcoon_den", "catcoon_den", "idle"),
MakePlacer("ancient_altar_broken_placer", "crafting_table", "crafting_table", "idle_broken"),
MakePlacer("ancient_altar_placer", "crafting_table", "crafting_table", "idle"),
MakePlacer("walrus_camp_placer", "walrus_house", "walrus_house", "idle"),
MakePlacer("pond_placer", "marsh_tile", "marsh_tile", "idle"),
MakePlacer("pond_mos_placer", "marsh_tile", "marsh_tile", "idle_mos"),
MakePlacer("lava_pond_placer", "lava_tile", "lava_tile", "idle_lava"),
MakePlacer("pond_cave_placer", "marsh_tile", "marsh_tile", "idle_cave"),
MakePlacer("mermhouse_placer", "pig_house", "pig_house", "rundown"),
MakePlacer("resurrectionstone_placer", "resurrection_stone", "resurrection_stone", "idle_activate"),
MakePlacer("beehive_placer", "beehive", "beehive", "cocoon_small"),
MakePlacer("wasphive_placer", "wasphive", "wasphive", "cocoon_small"),
MakePlacer("spiderhole_placer", "spider_mound", "spider_mound", "full"),
MakePlacer("slurtlehole_placer", "slurtle_mound", "slurtle_mound", "idle"),
MakePlacer("batcave_placer", "batcave", "batcave", "idle"),
MakePlacer("monkeybarrel_placer", "barrel", "monkey_barrel", "idle"),
MakePlacer("tallbirdnest_placer", "egg", "tallbird_egg", "eggnest"),
MakePlacer("houndmound_placer", "houndbase", "hound_base", "idle"),
MakePlacer("cave_banana_tree_placer", "cave_banana_tree", "cave_banana_tree", "anim"),
MakePlacer("statueglommer_placer", "glommer_statue", "glommer_statue", "full"),
MakePlacer("babybeefalo_placer", "beefalo", "beefalo_baby_build", "idle_loop"),
MakePlacer("cave_entrance_open_placer", "cave_entrance", "cave_entrance", "open"),
MakePlacer("cave_exit_placer", "cave_stairs", "cave_exit", "open"),
MakePlacer("wormlight_plant_placer", "worm", "worm", "berry_idle"),
MakePlacer("flower_cave_placer", "bulb_plant_single", "bulb_plant_single", "idle"),
MakePlacer("flower_cave_double_placer", "bulb_plant_double", "bulb_plant_double", "idle"),
MakePlacer("flower_cave_triple_placer", "bulb_plant_triple", "bulb_plant_triple", "idle"),
MakePlacer("cactus_placer", "cactus", "cactus", "idle"),
MakePlacer("oasis_cactus_placer", "oasis_cactus", "oasis_cactus", "idle"),
MakePlacer("reeds_placer", "grass", "reeds", "idle"),
MakePlacer("klaus_sack_placer", "klaus_bag", "klaus_bag", "idle"),
MakePlacer("sacred_chest_placer", "sacred_chest", "sacred_chest", "closed"),
MakePlacer("rabbithole_placer", "rabbithole", "rabbit_hole", "idle"),
MakePlacer("pigtorch_placer", "pigtorch", "pig_torch", "idle"),
MakePlacer("oasislake_placer", "oasis_tile", "oasis_tile", "idle")